openapi: 3.0.0
info:
  title: Untitled API Document
  version: v0.0.0
servers:
  - url: https://jsonplaceholder.typicode.com/
paths:
  /posts:
    get:
      summary: get all
      operationId: getAll
      responses:
        '200':
          description: A JSON array of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
                    id:
                      type: integer
                    title:
                      type: string
                    body:
                      type: string
